WDP190202-16
Johny1010/WDP-1902-02 pull request #10
Opened 2019-03-05 15:51 UTC by matuzalema

Opis problemu:
Brak RWD stopki
Rozwiązanie:
- dodałam media query. Na dużych ekranach są 4 kolumny, na tabletach 2 a na tel 1 - zrobiłam to dzięki flex-basis
- copyright oraz socialmedia są na dużych ekranach obok siebie, na mniejszych pod copyright są socialmedia

2019-03-06 08:09 UTC, Varenthein requested changes
Czy nie dało się tego zrobić prościej? Bootstrap ma gotowe klasy do RWD. Może dałoby się osiągnąc taki efekt dzięki nim, zamiast dodawać nowy kod? :) Co o tym sądzisz?

2019-03-06 08:22 UTC, przemyslawjurkiewicz commented
Nie wiem czy tylko u mnie, ale na tylko dwa pierwsze divy ustawiają się obok siebie.
Wygląda to tak: https://scr.hu/4PPZpdV.

2019-03-06 15:08 UTC, matuzalema commented
Bootstrap to dobry pomysł:) Poprawiłam

2019-03-08 08:50 UTC, Varenthein commented
Wygląda to już ładnie, ale co byś powiedziała na to, żeby wycentrować jeszcze treść? Wyglałoby to chyba ładniej :)

2019-03-12 12:56 UTC, michal-bootcamp commented
@matuzalema od siebie dodam jeszcze zebys zmienila docelowy branch z master na develop

2019-03-13 08:58 UTC, matuzalema commented
Wycentrowałam text i img przy małych rozdzielczościach. Zmieniłam docelowy branch na develop

2019-03-13 12:32 UTC, Varenthein approved these changes

2019-03-13 12:33 UTC, merged