WDP190202-18
Johny1010/WDP-1902-02 pull request #14
Opened 2019-03-08 11:26 UTC by przemyslawjurkiewicz

Karty produktów w sekcji "New furniture" mają być slajdami w karuzeli. 

**Wymagania:** 
- na raz na ekranie ma się pojawiać tyle elementów, ile mieści się w jednym rzędzie (po zaimplementowaniu RWD, czyli 1-4 w zależności od trybu)
- zawsze ma być widoczny tylko 1 wiersz
- kropki po prawej (obok listy kategorii) mają się generować dynamicznie, w zależności od tego ile "ekranów" jest do przewinięcia (np. 8 produktów po 2 w rzędzie, oznacza że będą 4 kropki, po kliknięciu pierwszej widać produkty 1 i 2, po kliknięciu drugiej - 3 i 4, etc.)
- Klient podał przykład https://github.com/ganlanyuan/tiny-slider, ale możemy wybrać inny, pod warunkiem że będzie spełniał wymagania (no i bez jQuery)
- slider ma być swipe'owalny (czyli przewijany przesunięciem palca po ekranie) niezależnie od rozdzielczości ekranu, a najlepiej jakby się też dało myszką złapać i przewinąć, tylko to nie może być zbyt czułe, żeby bez problemu dało się kliknąć guziki na kartach produktów

**Rozwiązanie:**

- skorzystałem z tiny-lider - dodałem odnośniki w index.html
- w 50_section-products.html zmieniłem klasą row na my-slider oraz dodałem klasę slider-item do kart z produktami - zgodnie z dokumentacją tiny-slidera.
- w carousel.js są zdefiniowane opcje slidera
- w app.js dopisałem funkcję dodającą odpowiednią ilość kropek w nawigacji slidera
- dodałem też funkcję które przebudowują slidera i kropki po zmianie szerokości.
- niestety musiałem wyłączyć lint-staged w package.json ponieważ nie chciał przejść commit z carousel.js 
(błąd - brak zdefiniowanego tns, który jest definiowany w tiny-slider.js pobieranym w index.html)

2019-03-09 12:32 UTC, krollukasz requested changes

2019-03-09 12:32 UTC, krollukasz commented on src/partials/50_section-products.html
> +      <div class="ol-md-3 col-sm-6 col-xs-12 slider-item">
Wkradła się tu drobna literówka w klasie dla średnich średnich szerokości. Wymaga poprawy we wszystkich elementach z tą klasą

2019-03-09 12:32 UTC, krollukasz commented on src/scripts/carousel.js
> +    },
Nie bardzo rozumiem, czemu zastosowana jest tu akurat taka wartość dla breakpointu ? Nie powinno to być 576 ?

2019-03-11 07:11 UTC, przemyslawjurkiewicz commented on src/scripts/carousel.js
> +    },
Dziękuję za uwagi - poprawione.

2019-03-12 08:52 UTC, przemyslawjurkiewicz commented
**Ostatnie commity wyjaśnienie co zmieniłem:**

- przywróciłem oryginalne ustawienia linta (wiem nie powinienem tego wcześniej zmieniać :) )
- z index.html wywaliłem odwołania do zewnętrznych zasobów tiny-slidera zarówno dla .css jak i .js
- dodałem do style.scss import styli dla tiny-slidera z pliku _tiny-slider.scss który skopiowałem z biblioteki tiny-slidera (teraz mamy wszystko w jednym pliku .css)
- w pliku carousel.js zaimportowałem moduł - co jest zgodne z dokumentacją parcel oraz dokumentacją tiny-slidera. Co pozwoliło pozbyć się błędów wykazywanych przez linta i odwołania do zewnętrznych zasobów w index.html
- **Powoduje to obowiązek doinstalowania tiny-slidera (dependencies dodane w package.json)**

2019-03-13 00:26 UTC, krollukasz approved these changes
Jest super :)

2019-03-13 09:09 UTC, michal-bootcamp requested changes
wyrównaj sie z developem, rozwiaz konflikty i jeszcze raz przetestuj slider na roznych szerokosciach

2019-03-13 11:26 UTC, michal-bootcamp approved these changes

2019-03-13 11:27 UTC, michal-bootcamp commented
@przemyslawjurkiewicz jak dla mnie mozesz mergowac do developa :)

2019-03-13 11:37 UTC, przemyslawjurkiewicz commented
OK to merge go :)

2019-03-13 11:38 UTC, merged