WDP190202-11
Johny1010/WDP-1902-02 pull request #15
Opened 2019-03-09 15:46 UTC by krollukasz

**Opis problemu:**
Strona sypie się w trybach responsive. Klient nie ma designów RWD, więc trzeba zrobić na własną rękę. 
Ten task dotyczy menu głównego (wyszukiwanie i "Home", etc.) 
Na tabletach wyszukiwanie ma być pod menu, a na mniejszych ekranach ma być wyszukiwanie i obok niego ikona mobilnego menu, które po rozwinięciu ma pokazywać dropdown przykrywający treść strony. 

**Rozwiązanie:**
- w pliku 10_header.html dodałem klasy pomocnicze i element span zawierający ikonę rozwijanego menu
- w pliku header.scss dodałem media queries dla średnich i małych szerokości, ustawiłem w nich odpowiednie właściwości dla poszczególnych elementów
- w pliku app.js dodałem skrypt obsługujący rozwijanie menu na urządzeniach mobilnych

**Uwaga:** Po akceptacji klienta zamieniłem miejscami menu i pole wyszukiwania wyświetlane na tabletach. Takie ustawienie zapewnia większą czytelność i ułatwia korzystanie z menu

2019-03-11 08:29 UTC, michal-bootcamp requested changes
na firefox tryb mobile szerokosc 320 lupa przyslania hamburger, ze nie mozna w niego kliknac: https://scr.hu/oppvMB6

2019-03-12 08:22 UTC, krollukasz commented
Poprawiłem błąd zgodnie z uwagą. Do rozwiązania problemu wykorzystałem pozycjonowanie bezwzględne dla ikony przycisku.

2019-03-12 12:54 UTC, michal-bootcamp commented
poczekam jeszcze na review od kogos z zespolu :)

2019-03-13 07:58 UTC, przemyslawjurkiewicz commented
Wygląda bardzo dobrze 👍 
Jedyne na co możesz zwrócić uwagę przy następnych taskach to wykorzystanie klas Boostrapa, 
do ustawień chociażby  flexa przy różnych rozdzielczościach (https://getbootstrap.com/docs/4.3/utilities/flex/)

2019-03-13 08:01 UTC, przemyslawjurkiewicz approved these changes
Wygląda bardzo dobrze 👍
Jedyne na co możesz zwrócić uwagę przy następnych taskach to wykorzystanie klas Boostrapa,
do ustawień chociażby flexa przy różnych rozdzielczościach (https://getbootstrap.com/docs/4.3/utilities/flex/)

2019-03-13 09:00 UTC, michal-bootcamp approved these changes

2019-03-13 09:01 UTC, merged

2019-03-13 09:21 UTC, krollukasz commented
Dziękuję @przemyslawjurkiewicz :)
Co do kwestii, na którą zwróciłeś mi uwagę, to faktycznie, na początku chciałem zrobić to za pomocą przygotowanych klas bootstrapa. Ale nie mogłem osiągnąć zamierzonego efektu, więc zdecydowałem się na powyższe rozwiązanie.
Dziękuję Ci za podrzucony link :+1: 
Zapoznam się z nim dokładniej i spróbuję wykorzystać przy kolejnych zadaniach