Wdp190202-5
Johny1010/WDP-1902-02 pull request #2
Opened 2019-02-28 11:10 UTC by przemyslawjurkiewicz

Opis problemu:
Brak ostylowanych stanów "ulubiony" oraz "dodany do porównania". Te stany mogą być dodane na stałe poprzez dodanie klasy "active" na buttonie.
W podglądzie projektu musi być co najmniej po jednym produkcie, który ma klasy active: 
    na żadnym z tych buttonów
    tylko na "ulubiony"
    tylko na "dodany do porównania"
    na obu buttonach
Rozwiązanie:
    * dodałem style dla clasy .active button.scss 
    * dodoałem klasę .active dla linków w divie klasy outlines w celu 
       pokazania klientowi ich działania.

2019-03-01 08:40 UTC, przemyslawjurkiewicz commented
W ostatnim commicie naprawiłem błędy "ortograficzne" wcięcia cudzysłowy.
Błędy wykazane w skrypcie sprawdzającym, który zaczął mi działać :)

2019-03-03 16:40 UTC, michal-bootcamp requested changes

2019-03-03 16:40 UTC, michal-bootcamp commented on src/sass/components/_button.scss
> +.active {
selektor klasy `active` jest zbyt ogolny, psuje inne elementy: https://scr.hu/222LWlv

2019-03-03 16:40 UTC, michal-bootcamp commented on src/scripts/app.js
> +        this.className += ' active';
moze zamiast calego ifa moznaby uzyc `classList.toggle`?

2019-03-03 16:40 UTC, michal-bootcamp commented on src/sass/components/_button.scss
> +  border: none;
brak bordera sprawia, ze przycisk z klasa `active` jest mniejszy

2019-03-03 18:06 UTC, przemyslawjurkiewicz commented on src/sass/components/_button.scss
> +  border: none;
Dziękuję za uwagi.
Poprawiłem i jednocześnie zmieniłem styl dla .active  na bardziej delikatny.
Zmienia się kolor ikonki a nie całe tło. Moim zdaniem jest ładniej.

2019-03-04 09:51 UTC, michal-bootcamp requested changes
do stanu `active` dodaj jeszcze border w tym samym kolorze co font i bedzie git

2019-03-04 13:19 UTC, merged