WDP190202-9
Johny1010/WDP-1902-02 pull request #33
Opened 2019-03-21 11:10 UTC by krollukasz

**Opis problemu**
Klient chce, żeby wszystkie efekty hover na guzikach itd. (wszędzie gdzie na hover zmienia się kolor tła, tekstu lub ikon, etc.) były animowane i takie same dla wszystkich elementów. Co więcej, będzie chciał łatwo zmieniać czasy tych animacji (globalnie dla wszystkich elementów). Może potrzebować, żeby czas animacji koloru tła i czas animacji koloru tekstu/ikony były różne. 

Nie wiemy czy klient będzie pracował na plikach Sassa, więc robimy to przez extendowanie placeholdera. Extenda trzeba będzie dodać do styli każdego z hoverowanych elementów (ale tylko do nich). 

Wstępnie ustawiamy czasy animacji na 250ms.

**Rozwiązanie**
- utworzyłem plik `_placeholder.scss` zawierający rozszerzenie dla elementów mających efekt na `:hover` oraz linków
- w pliku dodałem ustawienia animacji dla tekstu i tła
- czasy animacji zdefiniowałem w pliku `_variables.scss` aby klient miał do nich dostęp w jednym miejscu
- dodałem utworzony @extend %animation w plikach `_button.scss` i `_feature-box.scss`

2019-03-21 12:18 UTC, przemyslawjurkiewicz commented
Wygląda bardzo dobrze. Działa jak należy. 👍 

Można by co prawda zrobić to prościej bez zmiany plików _button.scss i _feature-box.scss.
W pliku _placeholder.scss:
```
:hover,
:hover * {
  @extend %animation;
}
``` 
i po robocie. Ale to czepianie się ;)
A i duży plus za naprawę w header 👍

2019-03-21 12:59 UTC, krollukasz commented
Dziękuję Przemek, bez Twojej podpowiedzi by się nie udało ;)
Przyznam, że tego zapisu, który proponujesz
```
:hover * {
  @extend %animation;
}
```
nie próbowałem. Ale to słuszna uwaga :)
Co do header'a to nawet nie sam brak klamry `}` zwrócił uwagę, ale dziwnie ułożone wcięcia.

2019-03-21 13:22 UTC, przemyslawjurkiewicz approved these changes

2019-03-21 18:32 UTC, michal-bootcamp requested changes
zmien jeszcze prosze docelowy branch

2019-03-21 18:50 UTC, michal-bootcamp requested changes
popraw jeszcze prosze efekt hovera na `dropdown-menu` w `menu-bar` (ramka pojawia sie najpierw) oraz w `section--features` (tekst zmienia kolor wczesniej)

2019-03-23 13:51 UTC, krollukasz commented
Poprawiłem zgodnie z uwagami. Dodałem ekstendowanie animacji dla tekstu w `section--features` oraz dla linków w `menu-bar`

2019-03-23 18:57 UTC, michal-bootcamp approved these changes

2019-03-23 18:57 UTC, merged