Add crossed out old price
Johny1010/WDP-1902-02 pull request #5
Opened 2019-03-01 17:56 UTC by przemyslawjurkiewicz

**Opis problemu:**
Na karcie produktu ma być możliwość dodania starej ceny, która ma być przekreślona. 
Tylko przy niektórych produktach będzie stara cena.

**Rozwiązanie:**
- do diva klasy .price dodałem diva z klasą .old-price
- dodałem style dla klasy .price i klasy .old-price

2019-03-01 18:54 UTC, Varenthein commented
Tytuł PR-a powinien być taki sam jak nazwa brancha i tasku.

2019-03-01 19:00 UTC, przemyslawjurkiewicz commented
Dzięki przeoczyłem.

2019-03-01 19:03 UTC, Varenthein requested changes
Kreska line-trhrough ma pomarańczowy kolor. Zgodnie z designem powinien on być taki sam jak kolor samej starej ceny.

2019-03-01 19:04 UTC, Varenthein requested changes

2019-03-01 19:04 UTC, Varenthein commented on src/sass/components/_product-box.scss
> +    font-weight: 600;
Starajmy się używać jednego formatu kolorów. Skoro wszędzie był hex, to niech będzie też tutaj,

2019-03-01 20:19 UTC, przemyslawjurkiewicz commented on src/sass/components/_product-box.scss
> +    font-weight: 600;
OK. Poprawione

2019-03-05 09:47 UTC, przemyslawjurkiewicz commented
Zmieniłem wyświetlanie znaczka SALE.

2019-03-06 07:42 UTC, merged