WDP190202-10
Johny1010/WDP-1902-02 pull request #6
Opened 2019-03-04 12:31 UTC by matuzalema

**Opis problemu:**
Obecnie menu jest zrobione na elemencie <select>. Powinno być zrobione inaczej, aby była możliwość rozwijania po najechaniu myszką. 
**Rozwiązanie:**
- zmieniłam element <select> na <nav class="select"> zawarłam w nim listę,
- po akcji hover na ul<li zagnieżdżona wewnątrz lista rozwija się,
- zmieniłam w stylach nazwę selektora select na .select

2019-03-06 08:15 UTC, Varenthein requested changes
Wygląd końcowy moim zdaniem niezbyt pasuje do reszty designu.

Co powiesz na takie cos?

![image](https://user-images.githubusercontent.com/13353257/53865775-442cd300-3ff0-11e9-87f9-7ddf8dfb121f.png)

Myślę, że pasowałoby bardziej do reszty :)

2019-03-06 08:15 UTC, Varenthein commented on src/partials/10_header.html
> +                    <ul>
Nie widzę sensu, żeby robić tu listę w liście, skoro w tej pierwszej jest tylko jeden element. To moze byc nawet zwykły div.

```
div
  select category
  ul
    ...
```

2019-03-06 08:15 UTC, Varenthein commented on src/sass/components/_header.scss
> +                }
Zawsze w projekcie oddzielaliśmy regułki linią przerwy. Trzymajmy się tego nadal.

2019-03-07 11:34 UTC, matuzalema commented
Poprawiłam wg designu

2019-03-08 08:46 UTC, Varenthein requested changes

2019-03-08 08:46 UTC, Varenthein commented on src/sass/components/_header.scss
> +              line-height: 1.9;
Padding lewy to 30px, a prawy 35px. Przez to treść inków nie jest do końca po środku.

2019-03-12 12:58 UTC, michal-bootcamp commented
@matuzalema zmien prosze docelowy branch z master na develop

2019-03-13 08:31 UTC, matuzalema commented
Zmieniłam docelowego brancha na develop

2019-03-14 19:42 UTC, Varenthein approved these changes

2019-03-14 19:42 UTC, merged