WDP190202-12
Johny1010/WDP-1902-02 pull request #7
Opened 2019-03-04 12:57 UTC by przemyslawjurkiewicz

**Opis problemu:**
Strona sypie się w trybach responsive. Klient nie ma designów RWD, więc trzeba zrobić na własną rękę. 
Ten task dotyczy górnego paska (z walutą, językiem, etc.) oraz bannera na którym jest logo i inne elementy. 
Na tabletach wygląda ok, ale na mobilkach trzeba poprawić: 
  **top bar:**  
- dropdowny po lewej mają pozostać bez zmian
- login i register mają być bez tekstów (tylko ikony)
- w razie potrzeby można zmniejszyć marginy/paddingi wszystkich elementów, ale tylko w trybach w których jest to potrzebne
- ta ikona menu po prawej na topbarze ma zostać, zarówno na mobilkach jak i desktopie, Klient później zdecyduje co chce tam mieć i czy zmieni się ikona
  **banner:**
-  po lewej ma być logo
-  po prawej koszyk (wyrównany do góry logo, czyli trochę wyżej niż jest)
-  po koszykiem ma być telefon (ikona i numer)
-  numer telefonu można zmniejszyć do 14px
**Rozwiązanie:**
- dodałem media query dla małych ekranów w pliku _header.scss
- dodałem lub podmieniłem klasy bootstrapa dla prawidłowego wyświetlania wyświetlania
  w pliku 10_header.html

2019-03-06 10:35 UTC, michal-bootcamp requested changes
1. wysokosc `top-bar` jest za duza w porownaniu z projektem
2. ogarnij prosze nastepujace kwestie:
- niech `help` nie spada do nowej linii przy szerokosci ekranu 320px
- dodaj odstepy miedzy elementami, zeby nie dotykaly siebie nawzajem i krawedzi kontenera
- dla najmniejszych szerokosci mozesz zmniejszyc troche logo zeby nie nachodzilo na telefon
- niech maksymalna liczba w koszyku (99999) nie wystaje poza ekran
screen do powyzszych: https://scr.hu/ZBBLqGX

2019-03-06 10:35 UTC, michal-bootcamp commented on src/partials/10_header.html
> +                ><i class="fas fa-user"></i>
zamkniecie nawiasu dla linka `>` przenies linie wyzej (rowniez w linkach nizej)

2019-03-06 13:48 UTC, przemyslawjurkiewicz commented on src/partials/10_header.html
> +                ><i class="fas fa-user"></i>
OK. Naprawione.
Przez przypadek przypałętał mi się plik 50_section-products.html, w którym też poprawiłem `>` , a którego nie powinno być w commicie. A nie wiem jak go s commita usunąć.

2019-03-11 08:36 UTC, michal-bootcamp requested changes
jest git, tylko nadal `top-bar` jest zbyt wysoki na desktopie w porownaniu do projektu: https://scr.hu/OJJNnp1

2019-03-12 07:20 UTC, przemyslawjurkiewicz commented
Dziękuję za uwagi.
Rzeczywiście wysokość była inna <p> się rozpychało marginesem.
Zmieniłem marginesy na 0 i teraz wysokość top bar = 55px jak na projekcie.

2019-03-12 12:50 UTC, michal-bootcamp commented
poczekam jeszcze na review od kogos z zespolu :)

2019-03-13 12:03 UTC, krollukasz reviewed
Wizualnie jest bardzo dobrze, świetna robota :)
Nie wiem tylko, czemu dzieje się tak, że przesuwają się domknięcia tagów ? W przypadku Arka też tak się zdarzyło. Podobno występuje to przy robieniu commitów ?
Widziałem, że u Ciebie w plikach poprawiałeś, niestety da się to jeszcze wyłapać w dosłownie chyba 4 miejscach.
Ale ogólnie jestem na tak, i może niepotrzebnie czepiam się takich szczegółów ? ;)

2019-03-18 21:24 UTC, krollukasz approved these changes
Wszystko wygląda i działa perfekcyjnie. Na każdym urządzeniu i w każdej przeglądarce.
Bardzo dobra robota :+1:

2019-03-18 23:04 UTC, michal-bootcamp approved these changes

2019-03-18 23:07 UTC, merged