WDP190202-1
Johny1010/WDP-1902-02 pull request #9
Opened 2019-03-05 11:41 UTC by matuzalema

**Opis problemu:**
Brak zdjęć w kartach produktów oraz w "ostatnio na blogu"
**Rozwiązanie problemu:**
- stworzyłam 2 foldery ze zdjęciami: blog i product-box,
- dodałam zdjęcia do kart produktów i do bloga,
- w kartach produktów usunęłam w scss padding a dodałam stałą wysokość zdjęć

2019-03-06 09:54 UTC, michal-bootcamp requested changes
dla spojnosci proponowalbym jeszcze zmienic rozszerzenie pliku `blog-2.jpeg` na `.jpg`

2019-03-06 09:54 UTC, michal-bootcamp commented on src/index.html
> +    z <module href="./src/partials/10_header.html"></module>
jakies "z" sie zaplatalo

2019-03-06 09:54 UTC, michal-bootcamp commented on src/partials/50_section-products.html
> +            <img src="images/product-box/chair-2.jpg" />
dorzuc alt

2019-03-06 09:54 UTC, michal-bootcamp commented on src/sass/components/_button.scss
> +  z-index: 1;
nie ma tu ustawionego `position` na inne niz statyczne wiec `z-index` jest niepotrzebny poniewaz i tak nie dziala

2019-03-06 09:54 UTC, michal-bootcamp commented on src/sass/components/_product-box.scss
> +      color: #ffffff;
mozesz skrocic do `#fff`

2019-03-06 09:57 UTC, michal-bootcamp commented
@matuzalema zmienilem tez docelowy branch z `master` na `develop` i pojawily sie konflikty, wiec prosze domerguj sobie developa do Twojego brancha i te konflikty rozwiaz :) w razie problemow pisz

2019-03-06 15:52 UTC, matuzalema commented
Poprawiłam, wprowadzone zmiany są w tytule commita

2019-03-07 14:56 UTC, michal-bootcamp commented
wszystko ok, zostaly tylko konflikty do rozwiazania jak widac nizej

Proponuje zrobic to tak:
1. zaktualizowac lokalnie branch develop, czyli `git pull` bedac na branchu `develop`
2. przelaczyc sie na branch `WDP190202-1`
3. domergowac branch `develop`: `git merge develop`
4. rozwiazac konflikty
5. wypushowac branch `WDP190202-1`

i konflikty na githubie powinny zniknac

2019-03-07 14:58 UTC, michal-bootcamp approved these changes

2019-03-11 14:50 UTC, merged